version: '3'

services:

  python:
    container_name: python
    image: python
    pull_policy: never
    build: ./python
    volumes:
      - dj-vol:/home/django-tutorial

networks:
  jeseo-net:
    driver: bridge

volumes:
  dj-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${VOL_PATH}
